set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree' 
Plugin 'vim-airline/vim-airline'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
set tabstop=4
set shiftwidth=4

map <C-n> : NERDTreeToggle<CR>

noremap <C-d> :sh<cr>

set encoding=utf-8

" Move through tabs with ctrl-l and ctrl-h
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>

" air-line
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
" airline symbols
"let g:airline_left_sep = '◻'
let g:airline_left_sep = ''
let g:airline_left_alt_sep = '◻'
"let g:airline_right_sep = '◻'
let g:airline_right_sep = ''
let g:airline_right_alt_sep = '◻'
let g:airline_symbols.branch = '◻'
let g:airline_symbols.readonly = '◻'
let g:airline_symbols.linenr = '◻'
" Enable airline top buffers bar
let g:airline#extensions#tabline#enabled = 1


" In insert mode, change cursor
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

colorscheme molokai
